server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fupobaobaowoya/cloud2020-config.git  #GitHub上面的git仓库名字
          ####搜索目录
          search-paths:
            - cloud2020-config
          username: fupobaobaowoya
          password: 19980326Clf
      ####读取分支
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka

